server:
  port: 8082

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 全局指定日期格式
    time-zone: GMT+8 # 时区
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: rootroot
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  servlet:
    multipart: # 文件上传配置
      enabled: true # 是否开启文件上传
      max-file-size: 10MB # 文件最大值
      max-request-size: 10MB # 请求最大值
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: is_delete # 逻辑删除字段 也可以配置在代码里

# 配置要在这里配置
minio:
  endpoint: http://localhost:9090
  accessKey: minio
  secretKey: minio123
  bucket-name: hello-minio


## springdoc-openapi项目配置
springdoc:
  default-flat-param-object: true # 调试页面默认展开参数
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
## knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn